[2023-09-10T13:46:10.692+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_pipeline.check_api_available manual__2023-09-10T13:46:08.778526+00:00 [queued]>
[2023-09-10T13:46:10.701+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: weather_pipeline.check_api_available manual__2023-09-10T13:46:08.778526+00:00 [queued]>
[2023-09-10T13:46:10.701+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-09-10T13:46:10.701+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2023-09-10T13:46:10.701+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-09-10T13:46:10.716+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): check_api_available> on 2023-09-10 13:46:08.778526+00:00
[2023-09-10T13:46:10.723+0000] {standard_task_runner.py:52} INFO - Started process 80 to run task
[2023-09-10T13:46:10.726+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'weather_pipeline', 'check_api_available', 'manual__2023-09-10T13:46:08.778526+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp91cw_kw1', '--error-file', '/tmp/tmp4f1a4b3g']
[2023-09-10T13:46:10.727+0000] {standard_task_runner.py:80} INFO - Job 26: Subtask check_api_available
[2023-09-10T13:46:10.792+0000] {task_command.py:371} INFO - Running <TaskInstance: weather_pipeline.check_api_available manual__2023-09-10T13:46:08.778526+00:00 [running]> on host dcd05770a650
[2023-09-10T13:46:10.871+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thinh pham
AIRFLOW_CTX_DAG_ID=weather_pipeline
AIRFLOW_CTX_TASK_ID=check_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-09-10T13:46:08.778526+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-10T13:46:08.778526+00:00
[2023-09-10T13:46:10.885+0000] {logging_mixin.py:115} INFO - API request was successful!
[2023-09-10T13:46:10.885+0000] {logging_mixin.py:115} INFO - Response:
[2023-09-10T13:46:10.885+0000] {logging_mixin.py:115} INFO - {"coord":{"lon":-0.1257,"lat":51.5085},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"base":"stations","main":{"temp":302.1,"feels_like":303.66,"temp_min":296.73,"temp_max":305.64,"pressure":1013,"humidity":57},"visibility":10000,"wind":{"speed":6.17,"deg":260},"clouds":{"all":100},"dt":1694353443,"sys":{"type":2,"id":2075535,"country":"GB","sunrise":1694323612,"sunset":1694370526},"timezone":3600,"id":2643743,"name":"London","cod":200}
[2023-09-10T13:46:10.885+0000] {python.py:173} INFO - Done. Returned value was: None
[2023-09-10T13:46:10.900+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=weather_pipeline, task_id=check_api_available, execution_date=20230910T134608, start_date=20230910T134610, end_date=20230910T134610
[2023-09-10T13:46:10.938+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-09-10T13:46:10.977+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
